export const products = [
    // DJ Speakers
    { id: 1, slug: "dj-1201", name: "DJ-1201", category: "dj-speakers", size: '12"', power: "400W", price: 12999, description: "High-power 12 inch DJ speaker for professional events", fullDescription: "The DJ-1201 is a professional-grade 12-inch DJ speaker designed for high-power audio delivery. With 400W of power, this speaker delivers crystal-clear sound with deep bass response. Perfect for events, clubs, and outdoor venues.", features: ["400W RMS Power", "12-inch Woofer", "High-frequency Tweeter", "Durable Cabinet", "Professional Crossover"], specs: { impedance: "8 Ohm", frequency: "45Hz - 20kHz", sensitivity: "96dB", weight: "18kg" }, image: "/dj-challenger.jpg" },
    { id: 2, slug: "dj-1501", name: "DJ-1501", category: "dj-speakers", size: '15"', power: "600W", price: 18999, description: "Premium 15 inch DJ speaker with deep bass response", fullDescription: "The DJ-1501 is our premium 15-inch DJ speaker that delivers powerful sound with exceptional bass response. At 600W, it's perfect for medium to large venues.", features: ["600W RMS Power", "15-inch Woofer", "Titanium Tweeter", "Heavy-duty Cabinet", "Speakon Connectors"], specs: { impedance: "8 Ohm", frequency: "40Hz - 20kHz", sensitivity: "98dB", weight: "24kg" }, image: "/dj-challenger.jpg" },
    { id: 3, slug: "dj-1801", name: "DJ-1801", category: "dj-speakers", size: '18"', power: "800W", price: 24999, description: "Professional 18 inch DJ speaker for large venues", fullDescription: "The DJ-1801 is our flagship 18-inch DJ speaker designed for large venues and professional applications. With 800W of power, it fills any space with rich, powerful sound.", features: ["800W RMS Power", "18-inch Woofer", "Compression Driver", "Reinforced Cabinet", "Bi-amp Ready"], specs: { impedance: "8 Ohm", frequency: "35Hz - 20kHz", sensitivity: "100dB", weight: "32kg" }, image: "/dj-challenger.jpg" },
    { id: 4, slug: "dj-1202", name: "DJ-1202", category: "dj-speakers", size: '12"', power: "500W", price: 14999, description: "Compact 12 inch speaker with excellent clarity", fullDescription: "The DJ-1202 offers exceptional sound clarity in a compact 12-inch form factor. With 500W of power, it's perfect for small to medium venues.", features: ["500W RMS Power", "12-inch Driver", "Compact Design", "Easy Transport", "Multiple Inputs"], specs: { impedance: "8 Ohm", frequency: "50Hz - 20kHz", sensitivity: "95dB", weight: "16kg" }, image: "/dj-challenger.jpg" },

    // PD Series
    { id: 5, slug: "pd-450", name: "PD-450", category: "pd-series", size: '12"', power: "450W", price: 11999, description: "Professional driver series speaker for clarity", fullDescription: "The PD-450 is part of our Professional Driver series, engineered for exceptional vocal clarity and mid-range performance.", features: ["450W RMS Power", "Optimized for Speech", "Wide Dispersion", "Professional Grade", "Easy Installation"], specs: { impedance: "8 Ohm", frequency: "55Hz - 18kHz", sensitivity: "94dB", weight: "15kg" }, image: "/dj-challenger.jpg" },
    { id: 6, slug: "pd-600", name: "PD-600", category: "pd-series", size: '15"', power: "600W", price: 15999, description: "Heavy-duty PD series with enhanced bass", fullDescription: "The PD-600 combines the clarity of our PD series with enhanced bass response. At 600W, it's suitable for music playback while maintaining excellent speech intelligibility.", features: ["600W RMS Power", "Enhanced Bass", "Clear Vocals", "Rugged Build", "Versatile Use"], specs: { impedance: "8 Ohm", frequency: "45Hz - 18kHz", sensitivity: "96dB", weight: "20kg" }, image: "/dj-challenger.jpg" },
    { id: 7, slug: "pd-750", name: "PD-750", category: "pd-series", size: '15"', power: "750W", price: 19999, description: "Premium PD series for professional setups", fullDescription: "The PD-750 represents the pinnacle of our PD series. With 750W of power and premium components, it delivers audiophile-grade sound.", features: ["750W RMS Power", "Premium Drivers", "Audiophile Grade", "Professional Connectors", "Touring Ready"], specs: { impedance: "8 Ohm", frequency: "42Hz - 20kHz", sensitivity: "97dB", weight: "23kg" }, image: "/dj-challenger.jpg" },
    { id: 8, slug: "pd-900", name: "PD-900", category: "pd-series", size: '18"', power: "900W", price: 27999, description: "Top-tier PD series with maximum output", fullDescription: "The PD-900 is our most powerful PD series speaker. With 900W and an 18-inch driver, it delivers massive sound output.", features: ["900W RMS Power", "18-inch Driver", "Maximum Output", "Tour-grade Design", "Advanced Cooling"], specs: { impedance: "4 Ohm", frequency: "38Hz - 20kHz", sensitivity: "99dB", weight: "35kg" }, image: "/dj-challenger.jpg" },

    // Challenger Series
    { id: 9, slug: "ch-1000", name: "CH-1000", category: "challenger-series", size: '12"', power: "1000W", price: 32999, description: "Flagship Challenger series speaker", fullDescription: "The CH-1000 is the entry point to our legendary Challenger series. With 1000W of power, it delivers the raw power professionals demand.", features: ["1000W RMS Power", "Heavy-duty Magnet", "Steel Frame", "Professional Terminals", "Road-worthy Design"], specs: { impedance: "8 Ohm", frequency: "40Hz - 20kHz", sensitivity: "98dB", weight: "28kg" }, image: "/dj-challenger.jpg" },
    { id: 10, slug: "ch-1200", name: "CH-1200", category: "challenger-series", size: '15"', power: "1200W", price: 39999, description: "Heavy-duty Challenger with extended range", fullDescription: "The CH-1200 extends the Challenger range with a 15-inch driver and 1200W of power.", features: ["1200W RMS Power", "Extended Range", "Dual Voice Coil", "Reinforced Cone", "Premium Terminals"], specs: { impedance: "4 Ohm", frequency: "38Hz - 20kHz", sensitivity: "100dB", weight: "34kg" }, image: "/dj-challenger.jpg" },
    { id: 11, slug: "ch-1500", name: "CH-1500", category: "challenger-series", size: '18"', power: "1500W", price: 49999, description: "Ultimate Challenger series for professionals", fullDescription: "The CH-1500 is for professionals who accept nothing but the best. 1500W of power in an 18-inch format.", features: ["1500W RMS Power", "18-inch Driver", "Triple Magnet", "Cast Frame", "4-inch Voice Coil"], specs: { impedance: "4 Ohm", frequency: "35Hz - 20kHz", sensitivity: "102dB", weight: "42kg" }, image: "/dj-challenger.jpg" },
    { id: 12, slug: "ch-2000", name: "CH-2000", category: "challenger-series", size: '21"', power: "2000W", price: 64999, description: "Extreme power Challenger series speaker", fullDescription: "The CH-2000 is our most extreme offering. With 2000W of power and a massive 21-inch driver.", features: ["2000W RMS Power", "21-inch Monster Driver", "Industrial Grade", "Extreme SPL", "Competition Ready"], specs: { impedance: "2 Ohm", frequency: "30Hz - 18kHz", sensitivity: "105dB", weight: "55kg" }, image: "/dj-challenger.jpg" },

    // PA Series
    { id: 13, slug: "pa-200", name: "PA-200", category: "pa-series", size: '6"', power: "200W", price: 5999, description: "Compact PA speaker for small venues", fullDescription: "The PA-200 is a compact public address speaker perfect for classrooms, small offices, and conference rooms.", features: ["200W RMS Power", "Compact 6-inch", "Wall Mountable", "Clear Vocals", "Easy Install"], specs: { impedance: "8 Ohm", frequency: "80Hz - 18kHz", sensitivity: "90dB", weight: "5kg" }, image: "/dj-challenger.jpg" },
    { id: 14, slug: "pa-300", name: "PA-300", category: "pa-series", size: '8"', power: "300W", price: 7999, description: "Versatile PA speaker for medium events", fullDescription: "The PA-300 strikes the perfect balance between size and output. Ideal for medium-sized venues.", features: ["300W RMS Power", "8-inch Driver", "Versatile Use", "Ceiling Mount Option", "Low Profile"], specs: { impedance: "8 Ohm", frequency: "65Hz - 18kHz", sensitivity: "92dB", weight: "8kg" }, image: "/dj-challenger.jpg" },
    { id: 15, slug: "pa-400", name: "PA-400", category: "pa-series", size: '10"', power: "400W", price: 9999, description: "Professional PA series speaker", fullDescription: "The PA-400 is our professional-grade PA speaker. With a 10-inch driver and 400W of power.", features: ["400W RMS Power", "10-inch Woofer", "Horn Tweeter", "Flyable Design", "Professional Grade"], specs: { impedance: "8 Ohm", frequency: "55Hz - 19kHz", sensitivity: "94dB", weight: "12kg" }, image: "/dj-challenger.jpg" },
    { id: 16, slug: "pa-500", name: "PA-500", category: "pa-series", size: '12"', power: "500W", price: 12999, description: "High-power PA series for announcements", fullDescription: "The PA-500 delivers high-power performance for demanding PA applications.", features: ["500W RMS Power", "12-inch Full Range", "Long Throw", "Weather Resistant", "Pole Mount Compatible"], specs: { impedance: "8 Ohm", frequency: "50Hz - 20kHz", sensitivity: "96dB", weight: "16kg" }, image: "/dj-challenger.jpg" },

    // NEO Series
    { id: 17, slug: "neo-350", name: "NEO-350", category: "neo-series", size: '10"', power: "350W", price: 13999, description: "Lightweight neodymium speaker", fullDescription: "The NEO-350 uses advanced neodymium magnet technology to deliver powerful sound in a lightweight package.", features: ["350W RMS Power", "Neodymium Magnet", "Ultra Lightweight", "Easy Transport", "Excellent Efficiency"], specs: { impedance: "8 Ohm", frequency: "55Hz - 20kHz", sensitivity: "97dB", weight: "9kg" }, image: "/dj-challenger.jpg" },
    { id: 18, slug: "neo-500", name: "NEO-500", category: "neo-series", size: '12"', power: "500W", price: 17999, description: "Premium neodymium with superior clarity", fullDescription: "The NEO-500 combines neodymium efficiency with premium audio performance.", features: ["500W RMS Power", "Premium Neo Driver", "Superior Clarity", "Compact Size", "High Efficiency"], specs: { impedance: "8 Ohm", frequency: "50Hz - 20kHz", sensitivity: "98dB", weight: "12kg" }, image: "/dj-challenger.jpg" },
    { id: 19, slug: "neo-700", name: "NEO-700", category: "neo-series", size: '15"', power: "700W", price: 22999, description: "Professional neodymium series", fullDescription: "The NEO-700 is for professionals who need high power without the weight.", features: ["700W RMS Power", "15-inch Neo", "Pro-grade Build", "Lightweight Design", "Touring Ready"], specs: { impedance: "8 Ohm", frequency: "45Hz - 20kHz", sensitivity: "99dB", weight: "16kg" }, image: "/dj-challenger.jpg" },
    { id: 20, slug: "neo-1000", name: "NEO-1000", category: "neo-series", size: '18"', power: "1000W", price: 29999, description: "High-end neodymium magnet speaker", fullDescription: "The NEO-1000 represents the pinnacle of neodymium technology.", features: ["1000W RMS Power", "18-inch Neodymium", "Maximum Efficiency", "Professional Grade", "Road Worthy"], specs: { impedance: "4 Ohm", frequency: "38Hz - 20kHz", sensitivity: "101dB", weight: "22kg" }, image: "/dj-challenger.jpg" },

    // Amplifiers
    { id: 21, slug: "amp-1000", name: "AMP-1000", category: "amplifiers", power: "1000W", channels: "2 Channel", price: 15999, description: "Professional 2-channel amplifier", fullDescription: "The AMP-1000 is a professional 2-channel power amplifier delivering 500W per channel.", features: ["1000W Total Power", "2 Channel Design", "Class AB", "LED Indicators", "Protection Circuits"], specs: { thd: "<0.05%", snr: ">100dB", inputSensitivity: "1V", cooling: "Forced Air" }, image: "/dj-challenger.jpg" },
    { id: 22, slug: "amp-2000", name: "AMP-2000", category: "amplifiers", power: "2000W", channels: "2 Channel", price: 24999, description: "High-power stereo amplifier", fullDescription: "The AMP-2000 delivers serious power for demanding applications.", features: ["2000W Total Power", "Stereo/Bridge Modes", "Speakon Outputs", "Rack Mountable", "XLR Inputs"], specs: { thd: "<0.03%", snr: ">105dB", inputSensitivity: "0.775V", cooling: "Variable Speed Fan" }, image: "/dj-challenger.jpg" },
    { id: 23, slug: "amp-3000", name: "AMP-3000", category: "amplifiers", power: "3000W", channels: "2 Channel", price: 34999, description: "Professional grade amplifier", fullDescription: "The AMP-3000 is our professional-grade power amplifier.", features: ["3000W Total Power", "Class D Efficient", "DSP Ready", "Networked Control", "Advanced Protection"], specs: { thd: "<0.02%", snr: ">110dB", inputSensitivity: "Variable", cooling: "Advanced Cooling" }, image: "/dj-challenger.jpg" },
    { id: 24, slug: "amp-5000", name: "AMP-5000", category: "amplifiers", power: "5000W", channels: "4 Channel", price: 54999, description: "Heavy-duty 4-channel amplifier", fullDescription: "The AMP-5000 is our flagship amplifier. 4 channels with 1250W each.", features: ["5000W Total Power", "4 Channels", "Bridgeable", "Full DSP", "Network Control"], specs: { thd: "<0.01%", snr: ">115dB", inputSensitivity: "Adjustable", cooling: "Intelligent Cooling" }, image: "/dj-challenger.jpg" },

    // Driver Units
    { id: 25, slug: "du-50", name: "DU-50", category: "driver-units", power: "50W", type: "Tweeter", price: 1999, description: "High-frequency compression driver", fullDescription: "The DU-50 is a high-frequency compression driver designed for crisp, clear high-frequency reproduction.", features: ["50W RMS", "Titanium Diaphragm", "1-inch Exit", "High SPL", "Wide Dispersion"], specs: { frequency: "2kHz - 20kHz", impedance: "8 Ohm", sensitivity: "108dB", throat: "1 inch" }, image: "/dj-challenger.jpg" },
    { id: 26, slug: "du-75", name: "DU-75", category: "driver-units", power: "75W", type: "Mid-range", price: 2499, description: "Mid-range driver unit", fullDescription: "The DU-75 is a dedicated mid-range driver for systems requiring exceptional vocal reproduction.", features: ["75W RMS", "Polyimide Diaphragm", "1.4-inch Exit", "Smooth Response", "Low Distortion"], specs: { frequency: "800Hz - 18kHz", impedance: "8 Ohm", sensitivity: "110dB", throat: "1.4 inch" }, image: "/dj-challenger.jpg" },
    { id: 27, slug: "du-100", name: "DU-100", category: "driver-units", power: "100W", type: "Horn", price: 3499, description: "Professional horn driver", fullDescription: "The DU-100 is a professional horn driver for demanding applications.", features: ["100W RMS", "Aluminum Diaphragm", "2-inch Exit", "High Power", "Pro Grade"], specs: { frequency: "500Hz - 20kHz", impedance: "16 Ohm", sensitivity: "112dB", throat: "2 inch" }, image: "/dj-challenger.jpg" },
    { id: 28, slug: "du-150", name: "DU-150", category: "driver-units", power: "150W", type: "Compression", price: 4499, description: "Heavy-duty compression driver", fullDescription: "The DU-150 is our heavy-duty compression driver for high-power professional sound systems.", features: ["150W RMS", "Phenolic Diaphragm", "2-inch Exit", "Extreme SPL", "Touring Grade"], specs: { frequency: "400Hz - 18kHz", impedance: "16 Ohm", sensitivity: "115dB", throat: "2 inch" }, image: "/dj-challenger.jpg" },

    // Megaphones
    { id: 29, slug: "mg-25", name: "MG-25", category: "megaphones", power: "25W", range: "500m", price: 2999, description: "Portable megaphone for announcements", fullDescription: "The MG-25 is a portable megaphone perfect for crowd control, announcements, and emergency communication.", features: ["25W Output", "500m Range", "Built-in Siren", "Talk/Music Mode", "Battery Powered"], specs: { battery: "8x C cells", runtime: "8 hours", weight: "1.2kg", material: "ABS Plastic" }, image: "/dj-challenger.jpg" },
    { id: 30, slug: "mg-35", name: "MG-35", category: "megaphones", power: "35W", range: "700m", price: 3999, description: "High-power portable megaphone", fullDescription: "The MG-35 offers more power for larger areas.", features: ["35W Output", "700m Range", "Detachable Mic", "Shoulder Strap", "Whistle Function"], specs: { battery: "10x D cells", runtime: "10 hours", weight: "1.8kg", material: "Impact Resistant" }, image: "/dj-challenger.jpg" },
    { id: 31, slug: "mg-50", name: "MG-50", category: "megaphones", power: "50W", range: "1000m", price: 5499, description: "Professional megaphone with siren", fullDescription: "The MG-50 is our professional megaphone for demanding applications.", features: ["50W Output", "1km Range", "Multiple Sirens", "Recording Function", "Rechargeable Option"], specs: { battery: "Rechargeable/D cells", runtime: "12 hours", weight: "2.2kg", material: "Heavy Duty" }, image: "/dj-challenger.jpg" },
    { id: 32, slug: "mg-75", name: "MG-75", category: "megaphones", power: "75W", range: "1500m", price: 7999, description: "Heavy-duty megaphone for large areas", fullDescription: "The MG-75 is our most powerful megaphone.", features: ["75W Output", "1.5km Range", "USB Recording", "Multiple Tones", "Professional Grade"], specs: { battery: "Built-in Rechargeable", runtime: "15 hours", weight: "3.0kg", material: "Professional ABS" }, image: "/dj-challenger.jpg" },

    // Trolley Speakers
    { id: 33, slug: "ts-800", name: "TS-800", category: "trolley-speakers", size: '8"', power: "800W", battery: "Built-in", price: 8999, description: "Portable trolley speaker with battery", fullDescription: "The TS-800 is a portable trolley speaker with built-in battery.", features: ["800W PMPO", "Built-in Battery", "Bluetooth", "USB/SD Card", "Wireless Mic"], specs: { battery: "12V 7Ah", playTime: "4-6 hours", inputs: "Mic, Guitar, Aux", wheels: "Heavy Duty" }, image: "/dj-challenger.jpg" },
    { id: 34, slug: "ts-1000", name: "TS-1000", category: "trolley-speakers", size: '10"', power: "1000W", battery: "Built-in", price: 11999, description: "High-power trolley speaker", fullDescription: "The TS-1000 offers more power and longer battery life.", features: ["1000W PMPO", "Dual Wireless Mics", "LED Lights", "Remote Control", "Extended Battery"], specs: { battery: "12V 9Ah", playTime: "6-8 hours", inputs: "Multiple", wheels: "Reinforced" }, image: "/dj-challenger.jpg" },
    { id: 35, slug: "ts-1200", name: "TS-1200", category: "trolley-speakers", size: '12"', power: "1200W", battery: "Built-in", price: 14999, description: "Premium trolley speaker system", fullDescription: "The TS-1200 is our premium trolley speaker.", features: ["1200W PMPO", "12-inch Woofer", "Bluetooth 5.0", "RGB Lights", "Guitar Input"], specs: { battery: "12V 12Ah", playTime: "8-10 hours", inputs: "Full Range", wheels: "All Terrain" }, image: "/dj-challenger.jpg" },
    { id: 36, slug: "ts-1500", name: "TS-1500", category: "trolley-speakers", size: '15"', power: "1500W", battery: "Built-in", price: 18999, description: "Professional trolley speaker", fullDescription: "The TS-1500 is our professional trolley speaker.", features: ["1500W PMPO", "15-inch Driver", "Pro Wireless Mics", "DSP Effects", "Party Lights"], specs: { battery: "12V 15Ah", playTime: "10-12 hours", inputs: "Professional", wheels: "Professional Grade" }, image: "/dj-challenger.jpg" },
];

export const categories = [
    { name: "All Products", slug: "all" },
    { name: "DJ Speakers", slug: "dj-speakers" },
    { name: "PD Series", slug: "pd-series" },
    { name: "Challenger Series", slug: "challenger-series" },
    { name: "PA Series", slug: "pa-series" },
    { name: "NEO Series", slug: "neo-series" },
    { name: "Amplifiers", slug: "amplifiers" },
    { name: "Driver Units", slug: "driver-units" },
    { name: "Megaphones", slug: "megaphones" },
    { name: "Trolley Speakers", slug: "trolley-speakers" },
];

export const getCategoryName = (slug) => {
    const category = categories.find(c => c.slug === slug);
    return category ? category.name : "All Products";
};

export const getProductBySlug = (slug) => {
    return products.find(p => p.slug === slug);
};

export const getRelatedProducts = (product, limit = 4) => {
    return products
        .filter(p => p.category === product.category && p.id !== product.id)
        .slice(0, limit);
};

export const formatPrice = (price) => {
    return new Intl.NumberFormat('en-IN', {
        style: 'currency',
        currency: 'INR',
        maximumFractionDigits: 0,
    }).format(price);
};
